# fly.toml app configuration file generated for shopping-list-aalto on 2023-08-27T00:45:37+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shopping-list-aalto"
primary_region = "ams"

[build]

[http_service]
  internal_port = 7777
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
